[font.bold]
family = "Meslo LG M DZ"
style = "Bold"

[font.bold_italic]
family = "Meslo LG M DZ"
style = "Bold Italic"

[font.italic]
family = "Meslo LG M DZ"
style = "Italic"

[font.normal]
family = "Meslo LG M DZ"
style = "Regular"

[scrolling]
history = 10000

# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors


