#add_newline = false

format = """\
    $cmd_duration\
    $line_break\
    $username\
    $hostname\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $package\
    $php\
    $python\
    $line_break\
    $jobs\
    $character\
"""

[character]
format="$symbol "
success_symbol="[»](bold green)"
error_symbol="[»](bold red)"
vicmd_symbol="[❮](bold green)"

[cmd_duration]
min_time = 2500
format = "took [$duration]($style) "

[git_branch]
symbol = ""
style = "green"

[git_status]
untracked = ".‍"
modified = "#"
format = "($all_status$ahead_behind ) "
style = "dimmed green"

[hostname]
ssh_only = true
ssh_symbol = '~> '
format = '[$ssh_symbol$hostname]($style) in '
style='bold red'
disabled=false
