(add-to-list 'load-path "~/.doom.d/autoload")
(load! "+completion")
(load! "+core")
(load! "+editing")
(load! "+evil-utrack")
(load! "+keybinds")
(load! "+lang-go")
(load! "+local")
(load! "+magit")
(load! "+org")
(load! "+outshine")
(load! "+purpose")
(load! "+spotify")
(load! "+treemacs")
(load! "+ui")
(load! "+workspaces")
