#!/bin/bash
# inspo by xero

FULL=▓
EMPTY=░
EOL=▒ 
SIZE=7
C0="#000000"
C1="#222222"
C2="#1C596E"
C3="#B3291C"
C4="#3A3A3A"
C5="#efefef"
C6="#878787"
C7="#8787af"

draw()
{
	perc=$1
	SIZE=$2
	inc=$(( perc * SIZE / 100 ))
	out=
	thiscolor=
	for v in `seq 0 $(( SIZE - 1 ))`; do
		test "$v" -le "$inc"   \
		&& out="${out}#[fg=$C1]${FULL}" \
		|| out="${out}#[fg=$C1]${EMPTY}"
	done
	echo $out
}
load()
{
  upt=$(uptime | perl -n -e'/average: (\d+\.\d+)/ && print $1')
  comp="${upt//.*}"
	tc=$C0
	case 1 in
		$((comp < 1)))
			tc=$C2
			;;
		$((comp >= 2)))
			tc=$C3
			;;
	esac
	echo "#[fg=$tc]$upt"
}
front()
{
	echo "#[bg=$C7]#[fg=$C1]▓░"
}
echo `front` `load`