#! /bin/sh

# config options
bspc config border_width            1
bspc config top_padding             0
bspc config window_gap              2
bspc config split_ratio             0.63
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config history_aware_focus     true
bspc config auto_cancel             true

# desktops
bspc monitor ^1 -d web term file dev mus
bspc monitor ^2 -d im foo foo2 steam

bspc desktop ^1 -l monocle

# Rules
bspc rule -a Firefox desktop=^1
bspc rule -a Steam desktop=^9
bspc rule -a Skype desktop=^6
bspc rule -a psi-plus desktop=^6
bspc rule -a clementine desktop=^5
bspc rule -a lxappearance floating=on center=true
bspc rule -a nitrogen floating=on center=true

# colors
bspc config focused_border_color "#268bd2"
bspc config normal_border_color "#fdf6e3"
bspc config active_border_color "#fdf6e3"
bspc config focused_locked_border_color "#00C7D8"
bspc config normal_locked_border_color "#708D8F"
bspc config active_locked_border_color "#808C8D"
bspc config urgent_border_color "#cb4b16"
bspc config presel_border_color "#cb4b16"

# Autostart apps
compton &
nitrogen --restore
numlockx &
xsetroot -cursor_name left_ptr
#~/.dotfiles/.scripts/bspwm_panel.sh &

